RudsECom/Controllers/ProdSellerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RudsECom.AppDbContext;
using RudsECom.Models;
using RudsECom.ViewModel;

namespace RudsECom.Controllers
{
    public class ProdSellerController : Controller
    {
        private readonly DatabaseContext _context;

        public ProdSellerController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: ProdSeller
        public async Task<IActionResult> Index()
        {
              return View(await _context.Sellers.ToListAsync());
        }

        [HttpGet]
        public ViewResult ListSellers()
        {
            var model = new List<SellerViewModel>();

            foreach(var se in _context.Sellers.ToList())
            {
                var sellerModel = new SellerViewModel
                {
                    Id = se.SellerId,
                    SellerName = se.SellerName,
                    City = se.City,
                    Email = se.Email,
                    ContactNo = se.ContactNo
                };
                model.Add(sellerModel);
            }
            return View(model);
        }

        // GET: ProdSeller/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Sellers == null)
            {
                return NotFound();
            }

            var sellersModel = await _context.Sellers
                .FirstOrDefaultAsync(m => m.SellerId == id);
            if (sellersModel == null)
            {
                return NotFound();
            }

            return View(sellersModel);
        }

        // GET: ProdSeller/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ProdSeller/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,SellerName,City,Email,ContactNo")] SellersModel sellersModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sellersModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sellersModel);
        }

        // GET: ProdSeller/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Sellers == null)
            {
                return NotFound();
            }

            var sellersModel = await _context.Sellers.FindAsync(id);
            if (sellersModel == null)
            {
                return NotFound();
            }
            return View(sellersModel);
        }

        // POST: ProdSeller/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,SellerName,City,Email,ContactNo,ProductId")] SellersModel sellersModel)
        {
            if (id != sellersModel.SellerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sellersModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SellersModelExists(sellersModel.SellerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sellersModel);
        }

        // GET: ProdSeller/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Sellers == null)
            {
                return NotFound();
            }

            var sellersModel = await _context.Sellers
                .FirstOrDefaultAsync(m => m.SellerId == id);
            if (sellersModel == null)
            {
                return NotFound();
            }

            return View(sellersModel);
        }

        // POST: ProdSeller/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Sellers == null)
            {
                return Problem("Entity set 'DatabaseContext.Sellers'  is null.");
            }
            var sellersModel = await _context.Sellers.FindAsync(id);
            if (sellersModel != null)
            {
                _context.Sellers.Remove(sellersModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SellersModelExists(int id)
        {
          return _context.Sellers.Any(e => e.SellerId == id);
        }
    }
}

RudsECom/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using RudsECom.InterfacesAndSqlRepo;
using RudsECom.Models;
using RudsECom.ViewModel;

namespace RudsECom.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductsCRUD cRUD;
        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly IProdSellLinkCRUD psCRUD;

        public ProductsController(IProductsCRUD _cRUD, IWebHostEnvironment _webHostEnvironment, IProdSellLinkCRUD _psCRUD)
        {
            this.cRUD = _cRUD;
            this.webHostEnvironment = _webHostEnvironment;
            psCRUD = _psCRUD;
        }
        public IActionResult AllProducts()
        {
            var products = cRUD.GetProducts();
            return View(products);
        }
        public async Task<ViewResult> Details(int Id)
        {
            var prods = await cRUD.GetProductById(Id);
            return View(prods);
        }

        [HttpGet]
        public async Task<IActionResult> AddProduct(int SellerId, bool isSuccess = false, int prodId = 0)
        
        {
            ViewBag.SellerId = SellerId;
            var model = new ProductViewModel()
            {
                SellerId = SellerId
            };
            ViewBag.IsSuccess = isSuccess;
            ViewBag.ProductId = prodId;
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddProduct(ProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Photos != null)
                {
                    string folder = "ProductsImages/cover/";
                    model.PhotosUrl = await UploadImage(folder, model.Photos);
                }
                if (model.GalleryPhotos != null)
                {
                    string folder = "ProductsImages/gallery/";

                    model.Gallery = new List<GalleryModel>();
                    foreach (var file in model.GalleryPhotos)
                    {
                        var gallery = new GalleryModel()
                        {
                            Name = file.Name,
                            URL = await UploadImage(folder, file)
                        };
                        model.Gallery.Add(gallery);
                    }
                }


                int Id = await cRUD.AddNewProduct(model);
                if (model.SellerId != null)
                {
                    await psCRUD.LinkProdSell(model, Id);
                }
                if (Id > 0)
                {
                    return RedirectToAction(nameof(AddProduct), new { isSuccess = true, prodId = Id });
                }
            }
            return View();
        }
        private async Task<string> UploadImage(string folderPath, IFormFile file)
        {
            folderPath += Guid.NewGuid().ToString() + "_" + file.FileName;
            string serverFolder = Path.Combine(webHostEnvironment.WebRootPath, folderPath);
            await file.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
            return "/" + folderPath;
        }
        [HttpGet]
        public ViewResult Edit(int Id)
        {
            ProductsModel res = cRUD.GetProduct(Id);
            ProductViewModel products = new ProductViewModel()
            {
                ProductId = res.ProductId,
                ProdName = res.ProdName,
                ProdPrice = res.ProdPrice,
                Description = res.Description,
                Origin = res.Origin,
                City = res.City
            };
            return View(products);
        }
        [HttpPost]
        public IActionResult Edit(ProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                ProductsModel products = cRUD.GetProduct(model.ProductId);
                products.ProdName = model.ProdName;
                products.ProdPrice = model.ProdPrice;
                products.Description = model.Description;
                products.Origin = model.Origin;
                products.City = model.City;
                ProductsModel upProduct =  cRUD.updateProduct(products);
                return RedirectToAction("AllProducts");
            };
            return View();
        }
        public IActionResult Delete(int Id)
        {
            cRUD.delete(Id);
            return RedirectToAction("AllProducts");
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

RudsECom/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RudsECom</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RudsECom.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/output.css" asp-append-version="true" />

    @*CDN Links for bootstrap and jquery.*@
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RudsECom</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-link">
                                <form method="post" asp-controller="Account" asp-action="Logout">
                                    <button type="submit" style="width:auto" class="nav-link btn btn-link py-0">Logout</button>
                                </form>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ProdSeller" asp-action="Index">ProdSeller</a>
                            </li>
                        </ul>
                    }

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - RudsECom - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>